### ISSUE TITLE
[BUG] table line missing characters in windows terminal but not cmd

### ISSUE THREAD

**Issue by GSGBen** [willmcgugan/rich#186]
**Describe the bug**

Running `python -m rich` in the latest windows terminal outputs three ??? characters in the line under the column headings.

**To Reproduce**

![image](https://user-images.githubusercontent.com/15712321/88730499-83c20500-d179-11ea-8de1-833146b9ebac.png)

**Platform**

* Windows 10
* Windows terminal 1.1.2021.0
* Python 3.8.2
* Rich 4.2.0
* Happens with Cascadia, Cascadia Mono, Consolas. Assuming all fonts
* Doesn't happen in cmd/powershell/conemu

**Comment by willmcgugan** [comment]
This is actually a bug in Python itself https://bugs.python.org/issue37871

A workaround would be to chop Rich output in to parts smaller than the buffer size used by Python.

**Comment by willmcgugan** [comment]
Fixed in v4.2.1

**Comment by GSGBen** [comment]
Wow, thanks!

**Comment by willmcgugan** [comment]
Try 4.2.2

Rich now writes a line at a time, which seems to fix it. I can't reproduce the problem on Windows 10.

**Comment by GSGBen** [comment]
Tested on the original PC and it still happens, but tested on another Windows 10 one and it doesn't, so I'm chalking it up to an environment issue on this PC. Thanks for your work on this.
